function k = get_plot_keys
    k = {'t', 'pos_des_x', 'pos_des_y', 'pos_des_z', ...
         'vel_des_x', 'vel_des_y', 'vel_des_z', ...
         'acc_des_x', 'acc_des_y', 'acc_des_z', ...
         'yaw_des', 'yawrate_des', ...
         'pos_x', 'pos_y', 'pos_z', ...
         'vel_x', 'vel_y', 'vel_z', ...
         'roll', 'pitch', 'yaw', ...
         'omega_x', 'omega_y', 'omega_z', ...
         'trust_des', 'roll_des', 'pitch_des', 'yaw_des'
        };
end
